### ISSUE TITLE
Brak możliwości złożenia zgłoszenia

### ISSUE THREAD

**Issue by s20726** [pjwstkIOprojekt/backendv2#65]
![zgloszenieblad](https://user-images.githubusercontent.com/80711769/207686699-162e3a8a-1031-4c06-944f-2d9af6693b10.PNG)

POST http://localhost:8080/accident_report 500

w pliku załączone logi

[logi.txt](https://github.com/pjwstkIOprojekt/backendv2/files/10230789/logi.txt)

**Comment by s20462** [comment]
403 Forbidden: "Missing key - Get your FREE key at https://cloud.maptiler.com/account/keys/"] with root cause

brak klucza api do serwisu geokodującego

ustawię feature-flag w zależności czy ktoś chce lokalnie mieć translacje koordynatów na adres, żeby nie bawić się w ustawianie kluczy przez każdego
